name: philo macOS/Ubuntu compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: philo_one
      run:  make re -C philo_one
      
    - name: philo_two
      run:  make re -C philo_two
    
  macos-build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: philo_one
        run:  make re -C philo_one
        
      - name: philo_two
        run:  make re -C philo_two
